name: Pull Request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git Config
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - name: Use Node.js
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
